### ISSUE TITLE
[Chat History] chat history is not encrypted

### ISSUE THREAD

**Issue by Jeeppler** [notsecure/uTox#1128] opened 2015-09-01 16:10 UTC
uTox saves the chat history in plain text files. The problem about that is, everybody who has access to the hard drive disk can access an manipulate the chat history between Alice and Bob easily. 
This is a big problem under all platforms.

**Comment by GrayHatter** [comment] 2015-09-01 17:03
This is a duplicate of another issue.

**Comment by GrayHatter** [comment] 2015-09-01 17:04
Please go :+1:  that issue @Jeeppler ?

**Closed by GrayHatter** 2015-09-01 17:03 UTC
