### ISSUE TITLE
Notifications sounds

### ISSUE THREAD

**Issue by zan22** [notsecure/uTox#624] opened 2014-10-19 19:32 UTC
- [x] Contact logs in
- [x] Contact logs out
- [ ] Contact request accepted
- [ ] Error
- [x] Incoming call
- [x] Incoming video call
- [x] ~~Log in~~
- [x] ~~Log out~~
- [ ] New contact request
- [x] New message
- [x] Outgoing call
- [x] Outgoing video call
- [ ] Transfer complete
- [ ] Transfer pending

**Comment by GrayHatter** [comment] 2015-03-12 03:23
#870 

Configurable notifications would be great. For now i only mention notification types for Windows

types of notifications:

flashing window (on top of systray)
flashing taskbar icon
audio notification
notification trigger:

chat message
incoming call
incoming file transfer
file transfer complete
friend request
Each notification trigger should have each type of notification as option

**Comment by aaannndddyyy** [comment] 2015-03-12 16:56
Or simply changing the name or avatar in the list, so I can see where new messages are.

**Comment by GrayHatter** [comment] 2015-04-03 02:40
sounds uTox might choose to use

http://www.zamaudio.com/mbox2/toxsounds.tgz

input neede!

**Comment by tsudoko** [comment] 2015-04-03 07:36
`contactrequestaccepted.wav` sounds weird, but nice. I'm just not sure if it's going to be associated with what it's supposed to notify about.
`transfer*.wav` seem too simple/quiet
Is there any point of having sounds for outgoing calls? I mean, the user has initiated them, so he knows that they're happening without any notifications. If it's really needed, it should at least be different (less loud?) from incoming ones.

**Comment by aaannndddyyy** [comment] 2015-04-03 23:01
I don't like them at all.
Especially the outgoing call. Should resemble more a phone or skype. 
And before sound notifications, there should be visual indications. What if the user has sound turned off?

**Comment by Nsheppard01** [comment] 2015-04-06 03:29
I am of the opinion that computers should only make noise when the user requests it, and never as a way for the computer to get the user's attention. The latter is without exception annoying, and in some cases can lead to the user just ignoring things (one of the causes of 3 mile island)

Audible indicators also have the problem of only being useful if the user is within earshot of the computer. There is no way for an audible indicator to inform a user of something which happened while they were not present, and many users turn off the volume or keep headphones plugged in and only listen to them when they want to do something that requires sound. They do this precisely because they don't like listening to every random beep the computer throws at them.

A phone ringing noise is probably a good idea for incoming calls (they have to be responded too immediately) but for everything else, visual indicators are much more useful as they are not obnoxious, and can inform the user of messages previously received. A user might be more likely to multitask and occasionally check back at a chat window than to sit waiting for a bing.

**Comment by tsudoko** [comment] 2015-04-06 10:50
Sure, I agree with that, but some people wanted more sounds, so...

**Comment by Nsheppard01** [comment] 2015-04-06 14:52
Well, the user should be able to customize/disable them.

**Comment by GrayHatter** [comment] 2015-04-07 10:41
it's kinda uTox's job to make noise, but I'll leave most of the sounds disabled by default too. Because while I think comparing IM app sounds to 3mile island is a little hyperbolic, I'd like to keep uTox as the least annoying it can be!

**Comment by GrayHatter** [comment] 2015-04-07 10:42
See also https://github.com/zamaudio/toxsounds

**Comment by nachfuellbar** [comment] 2015-11-12 09:44
Any news on this?

**Comment by GrayHatter** [comment] 2016-05-14 08:14
updated

if someone would be willing to move this list to the new repo, that would be awesome!

**Comment by GrayHatter** [comment] 2016-07-09 19:27
in audio.c theres' a few fxn and macros to allow you to create any tone you want. I'm going to close this because it's on the old repo

**Closed by GrayHatter** 2016-07-09 19:27 UTC
Labels: Audio/Video, bug, enhancement, Friends, groups, high_priority, msg, user_interface
