### ISSUE TITLE
uTox hogs the soundcard and camera all the time

### ISSUE THREAD

**Issue by calimeroteknik** [notsecure/uTox#845] opened 2015-02-16 17:03 UTC
Right at startup, µTox takes a handle on the audio output device and the webcam.
This is quite troublesome, since no other application can use the audio output, the audio input, or the webcam, even when utox doesn't use them at all for anything.

So I have to close utox, run another app that uses the audio or camera, and start utox again.
It's the only way I can listen to music while chatting or use my camera for something else.

Your mileage may vary, depending on whether or not you have a resampling mixer / sound server.
Platform: GNU/Linux with v4l2 and ALSA

I believe it would be excellent to open the audio and video devices only when needed (conversation, and maybe sound notifications if any), and close them afterwards.

**Comment by ElLamparto** [comment] 2015-02-17 12:20
There is already a ticket for that. However under Debian and Windows µTox takes a camera into exclusive use. It does not affect audio. Once a web site attempted to use my webcam/micro and since then I begun to like this bug... I think that it should be configurable in the settings.
By the way, you don't need to close Tox. It is enough to select in the Settings 'None' as input device.

**Comment by calimeroteknik** [comment] 2015-02-17 14:21
Oh! Apologies, I did look for a bugreport but didn't find any. Could you point it to me?

It does not affect your audio maybe, because you use a sound server such as pulseaudio or (less probably) jackd, or don't mind that ALSA's resampler, dmix, is on and destroying sound quality.
Oftentimes I need to run jackd out of the blue for midi mixing, or to hog my output device for clear sound (since with dmix, the sound is horrible).
That means every app must release the audio output when it doesn't use it, else I can't hog it with other software that needs that.

Sadly, I cannot choose no audio output device in the settings… Only for the input.
And anyway that's quite bothersome, it's the only app I have that doesn't release the audio by itself.

As for the camera, your browser always asks you! (except if you explicitly told it not to)
And if you're using adobe flash (bleh), you have settings for that.
So really, I don't get your point here. You should really fix your web browser's settings!

**Comment by MatejKovacic** [comment] 2015-04-21 12:57
I can confirm this issue. I have found out uTox 0.2.o (I am using it on Ubuntu 14.10) is accessing laptop camera all the time. If you run uTox and then try to run Cheese (app for video capturing), Cheese says that camera device is in use.

The fact is there is no video chat active in uTox, and it still is "blocking" camera.

**Comment by akhilman** [comment] 2015-05-13 07:30
qTox and uTox both keeps audio device open. It invisible because of pulse audio alows multiple clients to use same device. But it is not a good way to do things INHO. Open audio device uses cpu circles and disabl es power saving on some hardware.

**Comment by calimeroteknik** [comment] 2015-05-13 19:31
There is also that uTox is completely frozen at startup if I'm already using my audio device with a sound server for qsynth, for instance.
That's the case even if I choose another sound output in uTox's preferences; it still needs all of them(?) to be available at startup otherwise it hangs. Then it's fine, as long as I don't choose my sound card as the output.

**Comment by calimeroteknik** [comment] 2015-05-20 13:42
Collateral issue with my webcam: I was wondering why it was (physically) *hot* all the time, even not using it at all.
Answer found: utox is running. That was also what was reducing my battery life…

Same problem for a friend using windows 7.

**Comment by cebe** [comment] 2015-07-10 01:59
for the video part this will be fixed by #1101 (issue #628)

**Comment by calimeroteknik** [comment] 2016-02-29 11:00
Nice! The camera isn't hogged anymore in 31e8a7c. (though the pull request doesn't seem merged?)

This is becoming worse for sound though; utox now hogs the first soundcard even if I select a different sound card (so it would hog that other soundcard instead, that was my fix with 0.5).

**Comment by cebe** [comment] 2016-02-29 11:04
you are in the wrong repo. development is going on in https://github.com/GrayHatter/uTox for some time now. The PR is merged there.

**Comment by GrayHatter** [comment] 2016-04-25 00:27
I think this is fixed, if not please reopen here https://github.com/GrayHatter/uTox/issues

**Closed by GrayHatter** 2016-04-25 00:27 UTC
Labels: Audio/Video, bug, hardware_support, high_priority, Linux
