### ISSUE TITLE
Option - automatically minimize the uTox window during screen sharing

### ISSUE THREAD

**Issue by Jeeppler** [notsecure/uTox#1124] opened 2015-08-24 21:49 UTC
Offer an option which allows to automatically minimize the uTox window during screen sharing, to be able to see all other windows or the desktop.

**Comment by cebe** [comment] 2015-08-24 22:43
duplicate of #715

**Comment by tsudoko** [comment] 2015-08-25 01:26
Screen sharing != screenshot

**Comment by GrayHatter** [comment] 2015-08-25 03:59
Either this is a dup, or closing as wontfix. We might offer the option to minimize for a screenshot, but not for screen sharing during a video call.

**Closed by GrayHatter** 2015-08-25 03:59 UTC
